import type { OverlayStyle, ExportPreset } from '../types';

const base: Omit<OverlayStyle, 'presetId'> = {
  mode: 'route-only',
  mapOpacity: 0.25,
  routeColor: '#f5f1e6',
  lineThicknessPx: 2,
  lineOpacity: 0.85,
  lineStyle: 'solid',
  glow: false,
  directionalArrows: false,
  markerShape: 'dot',
  markerSizePx: 5,
  markerColor: '#f5f1e6',
  fontFamily: 'Inter',
  fontSizePx: 15,
  letterSpacingPx: 2,
  textOpacity: 0.92,
  textAlign: 'center',
  textColor: '#f5f1e6',
  textHalo: true,
  fields: {
    name: true,
    elevation: true,
    coordinates: false,
    distance: false,
    date: false,
    custom: false,
  },
  customText: '',
  tripDate: '',
  unit: 'ft',
};

export const PRESETS: Record<string, OverlayStyle> = {
  'himalayan-minimal': {
    ...base,
    presetId: 'himalayan-minimal',
    mode: 'route-only',
    lineThicknessPx: 1.5,
    lineOpacity: 0.25,
    glow: false,
    markerShape: 'dot',
    markerSizePx: 4,
    fontFamily: 'Inter',
    fontSizePx: 14,
    letterSpacingPx: 3,
    textOpacity: 0.9,
    fields: { name: true, elevation: true, coordinates: false, distance: false, date: false, custom: false },
  },
  minimal: {
    ...base,
    presetId: 'minimal',
    lineThicknessPx: 1,
    lineOpacity: 0.5,
    markerSizePx: 3,
    fontSizePx: 11,
    letterSpacingPx: 2,
    fields: { name: true, elevation: false, coordinates: false, distance: false, date: false, custom: false },
  },
  expedition: {
    ...base,
    presetId: 'expedition',
    lineThicknessPx: 2,
    lineOpacity: 0.9,
    directionalArrows: true,
    markerShape: 'circle',
    markerSizePx: 6,
    fontFamily: 'DM Sans',
    fontSizePx: 13,
    letterSpacingPx: 1.5,
    fields: { name: true, elevation: true, coordinates: true, distance: true, date: false, custom: false },
  },
  cinematic: {
    ...base,
    presetId: 'cinematic',
    lineThicknessPx: 1.25,
    lineOpacity: 0.35,
    glow: true,
    markerSizePx: 4,
    fontFamily: 'Montserrat',
    fontSizePx: 26,
    letterSpacingPx: 4,
    textOpacity: 1,
    fields: { name: true, elevation: true, coordinates: false, distance: false, date: false, custom: false },
  },
  gps: {
    ...base,
    presetId: 'gps',
    routeColor: '#7CFC9A',
    markerColor: '#7CFC9A',
    textColor: '#7CFC9A',
    lineThicknessPx: 1.5,
    lineOpacity: 0.95,
    lineStyle: 'dashed',
    directionalArrows: true,
    markerShape: 'circle',
    fontFamily: 'Inter',
    fontSizePx: 11,
    letterSpacingPx: 1,
    fields: { name: true, elevation: true, coordinates: true, distance: true, date: true, custom: false },
  },
  postcard: {
    ...base,
    presetId: 'postcard',
    lineThicknessPx: 2,
    lineOpacity: 0.8,
    lineStyle: 'dashed',
    markerShape: 'pin',
    markerSizePx: 8,
    fontFamily: 'Montserrat',
    fontSizePx: 20,
    letterSpacingPx: 3,
    fields: { name: true, elevation: true, coordinates: false, distance: true, date: true, custom: false },
  },
};

export const DEFAULT_PRESET_ID = 'himalayan-minimal';

export const EXPORT_PRESETS: ExportPreset[] = [
  { id: 'ig-portrait', label: 'Instagram Portrait (1080×1350)', width: 1080, height: 1350 },
  { id: 'ig-story', label: 'Instagram Story (1080×1920)', width: 1080, height: 1920 },
  { id: 'square', label: 'Square (1080×1080)', width: 1080, height: 1080 },
  { id: 'custom', label: 'Custom', width: 1080, height: 1350 },
];

export const DEFAULT_EXPORT_PRESET_ID = 'ig-story';
